"""Link skills to ESCO concepts (DR-05) using the public ESCO search API.

Resolved links are written to data/reference/esco_links.yaml, separate from skills.yaml, so the
hand-written vocabulary keeps its comments and every automatic match can be reviewed
(`checked: false` until someone confirms it).
"""

from __future__ import annotations

import json
import urllib.parse
import urllib.request
from collections.abc import Callable
from datetime import date
from pathlib import Path

import yaml

ESCO_SEARCH_URL = "https://ec.europa.eu/esco/api/search"

Fetch = Callable[[str], dict]


def http_get_json(url: str) -> dict:
    req = urllib.request.Request(url, headers={"Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)


def search_skill(query: str, fetch: Fetch = http_get_json) -> dict | None:
    """Return the best ESCO skill/knowledge match for `query`, or None."""
    params = urllib.parse.urlencode(
        {"text": query, "type": "skill", "language": "en", "limit": 5, "full": "false"}
    )
    data = fetch(f"{ESCO_SEARCH_URL}?{params}")
    results = data.get("_embedded", {}).get("results", [])
    if not results:
        return None
    # Prefer an exact (case-insensitive) title match; otherwise take ESCO's top-ranked result.
    exact = [r for r in results if r.get("title", "").lower() == query.lower()]
    best = (exact or results)[0]
    return {"uri": best["uri"], "label": best["title"]}


def load_links(path: Path) -> dict[str, dict]:
    if not path.is_file():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return data.get("links", {}) or {}


def resolve_links(
    skills: dict, links_path: Path, fetch: Fetch = http_get_json, refresh: bool = False
) -> tuple[int, list[str]]:
    """Look up ESCO links for skills that have none yet. Returns (resolved count, not found ids)."""
    links = load_links(links_path)
    resolved, not_found = 0, []
    for skill in skills.values():
        if not skill.esco_query:
            continue
        existing = links.get(skill.id)
        if existing and (existing.get("checked") or (existing.get("uri") and not refresh)):
            continue
        match = search_skill(skill.esco_query, fetch)
        if match is None:
            not_found.append(skill.id)
            links[skill.id] = {
                "uri": None,
                "label": None,
                "query": skill.esco_query,
                "resolved_on": date.today().isoformat(),
                "checked": False,
            }
            continue
        links[skill.id] = {
            **match,
            "query": skill.esco_query,
            "resolved_on": date.today().isoformat(),
            "checked": False,
        }
        resolved += 1
    header = (
        "# ESCO links per skill id, generated by `jobmarket reference resolve-esco`.\n"
        "# Review each entry and set checked: true when the concept fits. Edit uri/label by hand\n"
        "# to fix a wrong match; checked entries are never overwritten.\n"
    )
    body = yaml.safe_dump(
        {"links": dict(sorted(links.items()))}, allow_unicode=True, sort_keys=False, width=120
    )
    links_path.write_text(header + body, encoding="utf-8")
    return resolved, not_found
