"""The ESCO occupations that count as ICT, from the ISCO groups (DR-05).

EURES files every vacancy under one or more ESCO occupations, so we can ask it for ICT vacancies
instead of guessing from the title. The list is generated from the ISCO groups below and written
to data/reference/esco_occupations.yaml, which is what the pipeline reads: the groups are a
methodology choice and the file makes it reviewable.
"""

from __future__ import annotations

import json
import urllib.parse
import urllib.request
from pathlib import Path

import yaml

API = "https://ec.europa.eu/esco/api/resource/concept"

# ISCO unit groups counted as ICT. 352 (telecommunications and broadcasting technicians) is left
# out: those are installation and studio roles, not the work an HBO ICT programme prepares for.
ISCO_GROUPS = {
    "C133": "ICT service managers",
    "C251": "Software and applications developers and analysts",
    "C252": "Database and network professionals",
    "C351": "ICT operations and user support technicians",
}


def _get(uri: str) -> dict:
    url = f"{API}?uri={urllib.parse.quote(uri, safe='')}&language=en"
    request = urllib.request.Request(url, headers={"Accept": "application/json"})
    with urllib.request.urlopen(request, timeout=60) as response:
        return json.load(response)


def _occupations(uri: str, depth: int = 0) -> list[tuple[str, str]]:
    """Every occupation under an ISCO group, following the narrower concepts down."""
    links = _get(uri).get("_links", {})
    out = [(o["uri"], o.get("title", "")) for o in links.get("narrowerOccupation", [])]
    if depth < 3:
        for concept in links.get("narrowerConcept", []):
            out += _occupations(concept["uri"], depth + 1)
    return out


def fetch_ict_occupations() -> dict[str, list[dict[str, str]]]:
    """{ISCO group: [{uri, label}]} for the groups above, from the ESCO API."""
    out: dict[str, list[dict[str, str]]] = {}
    seen: set[str] = set()
    for group in ISCO_GROUPS:
        items = []
        for uri, label in sorted(
            _occupations(f"http://data.europa.eu/esco/isco/{group}"), key=lambda x: x[1]
        ):
            if uri in seen:
                continue
            seen.add(uri)
            items.append({"uri": uri, "label": label})
        out[group] = items
    return out


def write_yaml(path: Path, groups: dict[str, list[dict[str, str]]]) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    document = {
        "note": (
            "Generated by `jobmarket reference update-occupations`. These ESCO occupations are "
            "what we ask EURES for; a vacancy filed under one of them counts as ICT."
        ),
        "isco_groups": ISCO_GROUPS,
        "occupations": [
            {"isco": group, **item} for group, items in groups.items() for item in items
        ],
    }
    path.write_text(yaml.safe_dump(document, allow_unicode=True, sort_keys=False), encoding="utf-8")
    return sum(len(items) for items in groups.values())


def load_occupation_uris(path: Path) -> list[str]:
    if not path.is_file():
        return []
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return [o["uri"] for o in data.get("occupations", []) if o.get("uri")]
